import React from 'react'
import "../globals.css"
import { ThemeProvider } from '@/components/theme-provider'
import { Metadata } from 'next';
import Navbar from '@/components/shared/navbar';

export const metadata: Metadata = {
  title: "Startific",
  description: "Generated by create next app",
};
const AuthLayout = ({children}:{children:React.ReactNode}) => {
  return (
    <html lang="en">


    <body className='h-screen flex items-center justify-center'>
       <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
          >
          <Navbar />
      {children}
        </ThemeProvider>
      </body>
          </html>
  )
}

export default AuthLayout