import React from 'react'
import "../globals.css"
import { ThemeProvider } from '@/components/theme-provider'
import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "Startific",
  description: "Generated by create next app",
};
const AuthLayout = ({children}:{children:React.ReactNode}) => {
  return (
    <div className='h-screen flex items-center justify-center'>
       <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >

      {children}
        </ThemeProvider>
      </div>
  )
}

export default AuthLayout